service: ${env:APP_NAME}
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

useDotenv: true
configValidationMode: error

provider:
  name: aws
  architecture: arm64
  runtime: nodejs18.x
  memorySize: 128
  timeout: 3
  logRetentionInDays: 14
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:provider.stackName}
  stage: ${opt:stage, 'local'}
  profile: ${env:AWS_ACCOUNT_PROFILE}
  region: ${opt:region, env:AWS_APP_REGION}
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 100
  httpApi:
    cors: true
    disableDefaultEndpoint: ${env:AWS_APIGW_DISABLE_DEFAULT_ENDPOINT}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  stackTags:
    SITE: ${self:service}
    PRODUCT: ${self:service}
    STAGE: ${self:provider.stage}
    datadog: monitored
    service: ${env:APP_NAME}
    env: ${self:provider.stage}
  vpc:
    securityGroupIds:
      - ${env:AWS_VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:AWS_VPC_SUBNET_1_ID}
      - ${env:AWS_VPC_SUBNET_2_ID}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stackName}-*'
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:ReceiveMessage'
        - 'sqs:DeleteMessage'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:*'
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::${env:LESGO_AWS_S3_BUCKET}'
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource: 'arn:aws:s3:::${env:LESGO_AWS_S3_BUCKET}/*'
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: '*'

custom:
  path:
    app: src
    functions: config/functions
    resources: config/resources
  serverless-offline:
    port: 8888
    ignoreJWTSignature: true
  contentEncoding:
    contentCompression: 100
  dotenv:
    basePath: config/environments/

#
# Add functions here
#
functions:
  - ${file(${self:custom.path.functions}/utils.yml)}
  - ${file(${self:custom.path.functions}/sample-utils.yml)}
  - ${file(${self:custom.path.functions}/sample-s3.yml)}
  - ${file(${self:custom.path.functions}/sample-jwt.yml)}
  - ${file(${self:custom.path.functions}/sample-auth.yml)}
  - ${file(${self:custom.path.functions}/sample-dynamodb.yml)}
  - ${file(${self:custom.path.functions}/sample-sqs.yml)}
  - ${file(${self:custom.path.functions}/sample-secretsManager.yml)}
  - ${file(${self:custom.path.functions}/sample-commands.yml)}
  - ${file(${self:custom.path.functions}/sample-rdsMysqlProxy.yml)}
  - ${file(${self:custom.path.functions}/sample-elasticache-redis.yml)}
  # - ${file(${self:custom.path.functions}/sample-opensearch.yml)}

#
# Add resources here
#
resources:
  # - ${file(${self:custom.path.resources}/sample-vpc.yml)}
  - ${file(${self:custom.path.resources}/sample-dynamodb.yml)}
  - ${file(${self:custom.path.resources}/sample-sqs.yml)}
  # - ${file(${self:custom.path.resources}/sample-rdsProxy.yml)}
