sampleSecretsManagerGetSecretValue:
  handler: ${self:custom.path.app}/handlers/sample-secretsManager/getSecretValue.handler
  description: Test get secret value from Secrets Manager
  memorySize: 128
  timeout: 3
  reservedConcurrency: 1
  events:
    - httpApi:
        path: /v1/sample/secrets-manager
        method: GET
